#pragma once
// Hero
#define HERO_START_LEVEL 1
#define HERO_LEVEL_UP_FACTOR 1.2
#define HERO_EXPERIENCE_FOR_LEVEL_UP 100
#define HERO_MAX_NUMBER_SKILLS 4
#define HERO_KILL 1
#define HERO_DIE -1
#define SPEED_START 600
#define SPEED_MAX 550
#define SPEED_FACTOR 3
#define HERO_START_POSITION_X 6
#define HERO_START_POSITION_Y 38
// Skill
#define SKILL_LEVEL_FACTOR 1.1
#define SKILL_LEVEL_COOLDOWN_FACTOR 1
// Resources
#define RESOURCE_DAMAGE_TO_LOOT_GOLD 100
#define RESOURCE_DAMAGE_TO_LOOT_WOOD 200
#define RESOURCE_DAMAGE_TO_LOOT_DIAMONDS 300
#define RESOURCE_DURABILITY_GOLD 5000
#define RESOURCE_DURABILITY_DIAMONDS 1000
#define RESOURCE_DURABILITY_WOOD 5000
// Other
#define DEFAULT_XP_KILL_FACTOR 20
#define ARMOR_FACTOR 2
#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768